config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/profile", to: "pages#profile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show]
  get "/add_friend", to: "friendships#add_friend"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :events do
    resources :invitations, only: [:create, :update]
  end
  resources :friendships, only: [ :new, :create ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :invitations
  has_many :friendships
  has_many :askers, class_name: 'Friendship', foreign_key: 'asker_id'
  has_many :receivers, class_name: 'Friendship', foreign_key: 'receiver_id'
  has_many :events
  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def to_s
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/users/confirmation_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
        @friendship = Friendship.new
    end 

    def show
        @user = User.find(params[:id])
        @events = Event.where(user_id: @user.id)
        @friends = current_user.askers      
        @friendship_requests = Friendship.where(asker: current_user, receiver: @user)

    end 
end

app/views/users/index.html.erb
<div class="container mt-4">
  <div class="text-center">
  <div class="event-requests row">
    <h2> Users </h2>



    <% @users.each do |user| %>
      <% unless user==current_user %>
        <div class="event-requests-cards col-3 m-1">
          <div class="row">
            <div class="col-12">

              <%= link_to user_path(user) do  %>
                <% if user.photo.attached? %>
                  <%= cl_image_tag user.photo.key, crop: :fill,  class: "avatar-approved-user" %>
                <% else  %>
                  <%=image_tag("avatar.png", class: "avatar")%>
                <% end %>
              <% end  %>
              <div class="event-request-name p-2"> <%= user.first_name %> </div>
            </div>

          </div>


        <div class="row">
            <div class="col-12">
              <% if  Friendship.where(asker: current_user, receiver: user).empty? %>
                <%= render "friendships/form", user: user if current_user.askers.where(receiver_id: user.id, asker_id: current_user).empty? %>
              <% else %>
                <a disabled> Friend <i class="fa-sharp fa-solid fa-check"></i></a>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
   <% end  %>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class="container">

  <div class="row profile-header">
    <p> &larr; <%= link_to "Back to home page", root_path, class: "no-underline" %></p>
    <div class="profile-image col-2">
      <%= cl_image_tag @user.photo.key, width: 200, height: 200, class: "avatar-profile" %>
    </div>
    <div class="profile-info col-10">
      <h2><%= @user.first_name%> <%= @user.last_name %></h2>
      <p>Going to  <%= @events.count %> events </p>

         <% if @friendship_requests.empty? %>
         <%# <%= link_to "Add Friend",  add_friend_path(friend: @user), class: "btn btn-secondary" %>
         <% else %>
            <a disabled> Friend <i class="fa-sharp fa-solid fa-check"></i></a>
        <% end %>


    </div>
  </div>

  <div class="row user-events">
    <div class="col-md-6">
      <% @events.each do |event|%>
        <div class="card-event">

          <div class="row event-cards">
            <div class="d-flex align-items-center">
            <div class="event-image">
            <%= link_to(event_path(event)) do %>
              <%  if event.photo.attached?%>
                   <%= cl_image_tag event.photo.key, width: 400, height: 260, crop: :fill %>
                   <% else %>
                     <%=  image_tag('event_default.gif', width: 400, height: 260, crop: :fill) %>
                  <% end %>
            <% end %>
            </div>
            <% if event.invitations.where(status: "approved") %>
            <div class="d-flex flex-column">
              <div class="event-attributes">
                <h5 class="event-title"> 🎟 <%= event.title %></h5>
                <h5 class="event-date">🗓 <%= event.start_time.strftime("%A, %B %d at %H:%M")%></h5>
                <h5 class="event-location"> 📍 <%= event.location %></h5>
                <% if event.user == current_user %>
                <h5 class="event-host"> <%= cl_image_tag event.user.photo.key, width: 16, height: 16, class: "avatar-event-card"%> Hosted by you</h5>
                <% else %>
                <h5 class="event-host"> <%= cl_image_tag event.user.photo.key, width: 16, height: 16, class: "avatar-event-card"%> Hosted by <%= event.user%></h5>
                <% end %>
              </div>
              <div class="attend-event">
              <% if event.user == current_user %>
                  <%= link_to "Edit", edit_event_path(event), class: "btn btn-flat-slim" %>
                  <%= link_to "Delete", event_path(event), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-flat-secondary-slim" %>
                <% end %>
              <% end %>
              </div>
            </div>
          </div>
          </div>
        </div>
    <% end %>
    </div>

     <div class="col-md-6">
    <div class="calendar-container">
       <%= month_calendar(events: @events, end_attribute: :end_time) do |date, events| %>
       <%= date %>

      <% events.each do |event| %>
        <div class="calendar-event">
          <p><%= event.title %></p>
        </div>
       <% end %>
      <% end %>
    </div>
  </div>
  </div>
 <div class="row user-friends">
    <h2>Friends</h2>
    <div class="friend-photos">
    <% @friends.each do |friend| %>
    <%= link_to user_path(friend.receiver) do  %>
      <%= cl_image_tag friend.receiver.photo.key, width: 100, height: 100, crop: :fill, class: "avatar-friendship" if friend.receiver.photo.attached? %>
    <% end %>
    <% end %>

    <% @friendship_requests.each do |friend_request| %>
    <%= link_to user_path(friend_request.asker) do  %>
     <%= cl_image_tag friend_request.asker.photo.key, width: 100, height: 100, crop: :fill, class: "avatar-friendship" if friend_request.receiver.photo.attached? %>
    <% end %>

    <% end %>
   </div>


  </div>
</div>