config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/profile", to: "pages#profile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show]
  get "/add_friend", to: "friendships#add_friend"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :events do
    resources :invitations, only: [:create, :update]
  end
  resources :friendships, only: [ :new, :create ]
end

app/views/pages/home.html.erb
<div class="first-part">
     <div class="banner">
          <div class="title mt-8 ms-5">
               <h2><strong> Friendlendar </strong> </h2>
               <h6 class="ms-5"> Connect your calendar with your friend and share your event</h6>
          </div>
          <div class="banner-button-container">
               <%= link_to "Browse Events", events_path(@event), class: "fancy-button" %>
          </div>
          </div>
     </div>
</div>


<div class="arrow bounce">
     <i class="fa-solid fa-chevron-down fa-2x"></i>
     <a class="scroll-link" href="#scroll_anchor_cards">Find out more</small></a>
</div>

<div class="text-center" id="scroll_anchor_cards">

          <div class="friend">
               <h2 class="home"> What's friendlendar </h2>
               <p>
               Wanna meet your friends but you never know their availability? <br> Join Friendledar. <br> Find the most convenient time to meet up</p>
               <div class="intro">
               <h2 class="home"><strong> How it works </strong></h2>

               <div class="icons">
                    <div class="card">
                         <%=link_to image_tag("magic-wand.png", size: "150x150"),  new_event_path(@event) %>
                         <h3> Create an event </h3>
                         <h5>It's easy and fast! </h5>
                    </div>
                     <div class="card">
                         <%=image_tag("1051245.png", size: "150x150")%>
                         <h3> Share it with your friends  </h3>
                         <h5> Let your friends know what are your future plans</h5>
                    </div>
                    <div class="card">
                         <%=image_tag("1255623.png", size: "150x150")%>
                         <h3> Add in your calendar </h3>
                         <h5> It will be add automatically in your calendar </h5>
                    </div>
               </div>
          </div>
     </div>
</div >

app/views/pages/profile.html.erb
<div class="container">

  <div class="row profile-header">
    <p> &larr; <%= link_to "Back to home page", root_path, class: "no-underline" %></p>
    <div class="profile-image col-2">
      <%= cl_image_tag current_user.photo.key, width: 200, height: 200, class: "avatar-profile" %>
    </div>
    <div class="profile-info col-5">
      <h2><%= @current_user.first_name%> <%= @current_user.last_name %></h2>
      <p>Going to  <%= @events.count %> events </p>
      <div class="btn btn-flat"> Edit Profile </div>
    </div>

      <div class="profile-friends col-5">
      <h5>Top friends</h3>
        <div class="friend-photos">
          <div class = "d-flex flex-row">
            <% @friends.each do |friend| %>
            <%= link_to user_path(friend.receiver) do  %>
              <div class="friends-avatars"><%= cl_image_tag friend.receiver.photo.key, width: 70, height: 70, crop: :fill, class: "avatar-top-friend" if friend.receiver.photo.attached? %></div>
              <div class="avatar-name"><h5> <%= friend.receiver.first_name %></div>
            <% end %>
            <% end %>

            <%# <% @friendship_requests.each do |friend_request| %>
            <%# <%= link_to user_path(friend_request.asker) do  %>
            <%# <div class="friends-avatars"><%= cl_image_tag friend_request.asker.photo.key, width: 70, height: 70, crop: :fill, class: "avatar-top-friend" if friend_request.receiver.photo.attached? %>
            <%# <% end %>
            <%# <% end %>
          </div>
        </div>
      </div>
  </div>

  <div class="row user-events">
    <div class="col-md-6">
      <% @events.each do |event|%>
        <div class="card-event">

          <div class="row event-cards">
            <div class="d-flex align-items-center">
            <div class="event-image">
            <%= link_to(event_path(event)) do %>
              <%  if event.photo.attached?%>
                   <%= cl_image_tag event.photo.key, width: 400, height: 260, crop: :fill %>
                   <% else %>
                     <%=  image_tag('event_default.gif', width: 400, height: 260, crop: :fill) %>
                  <% end %>
            <% end %>
            </div>
            <% if event.invitations.where(status: "approved") %>
            <div class="d-flex flex-column">
              <div class="event-attributes">
                <h5 class="event-title"> 🎟 <%= event.title %></h5>
                <h5 class="event-date">🗓 <%= event.start_time.strftime("%A, %B %d at %H:%M")%></h5>
                <h5 class="event-location"> 📍 <%= event.location %></h5>
                <% if event.user == current_user %>
                <h5 class="event-host"> <%= cl_image_tag event.user.photo.key, width: 16, height: 16, class: "avatar-event-card"%> Hosted by you</h5>
                <% else %>
                <h5 class="event-host"> <%= cl_image_tag event.user.photo.key, width: 16, height: 16, class: "avatar-event-card"%> Hosted by <%= event.user%></h5>
                <% end %>
              </div>
              <div class="attend-event">
              <% if event.user == current_user %>
                  <%= link_to "Edit", edit_event_path(event), class: "btn btn-flat-slim" %>
                  <%= link_to "Delete", event_path(event), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-flat-secondary-slim" %>
                <% end %>
              <% end %>
              </div>
            </div>
          </div>
          </div>
        </div>
    <% end %>
    </div>

    <div class="col-md-6">
    <div class="calendar-container sticky-top">
       <%= month_calendar(events: @events, end_attribute: :end_time) do |date, events| %>
       <%= date %>

      <% events.each do |event| %>
        <% if event.user == current_user %>
          <div class="calendar-event p-1 mb-1">
            <p class="m-0"><%= event.title %></p>
          </div>
        <% else %>
          <div class="calendar-event-friend">
            <p><%= event.title %></p>
          </div>
        <% end %>
       <% end %>
      <% end %>
    </div>
  </div>
  </div>

</div>